# Page settings
baseurl = "http://localhost:8083"
title = "MK官网"
languageCode = "zh-cn"
theme = "my_elate"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "MK官网"
    home = "转链工具"
    work = "线报采集"
    testimonials = "俱乐部"
    services = "发单工具"
    about = "快捷工具"
    contact = "MK"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "第一家“线报淘客“解决方案提供商"
    subtitle = '淘客可以从0开始，解放双手，即刻盈利'
    subtitle2 = '基于线报特性，开发整合资源，完善淘客所有需求'
    subtitle3= '从线报源到转链发单到群管到引流全部自动化方案'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "QQ转链机器人"
    description = "监控直播采集群的消息，转链成你的返利，直播发到你的目的群里。支持淘宝，京东，拼多多，苏宁。支持采集QQ发送到微信群。"
    url = "#"
    icon = "icon-wrench"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "微信转链机器人"
    description = "微信端支持微信群采集转发到微信群，支持qq端采集转发到微信群。附带群管功能，自动回复，群聊私聊查券，一站式解决。"
    url = "#"

    icon = "icon-wrench"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "渠道代理版本"
    description = "支持多个返利账号多个PID，可以帮代理发单。开发中开发中。开发中开发中。开发中开发中"
    url = "#"
    icon = "icon-wrench"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "免费试用"
    description = "MK收费工具全部都是免费试用24小时，好用再付费。下载即试用，全功能无限制，口碑需要用产品积累！"
    url = "/jiaocheng.html"
    button = "下载"
    icon = "icon-bulb"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "后台协议"
    description = "全部采用后台协议，无需占用鼠标键盘和窗口，挂机的同时不影响你做其他的工作。高效稳定是做机器人的最基本的条件。"
    url = "/jiaocheng.html"
    button = "下载"
    icon = "icon-bulb"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "开发中。.开发中。开发中。开发中。开发中。开发中。开发中。开发中。开发中。"
    url = "/jiaocheng.html"
    button = "下载"
    icon = "icon-bulb"
    img = "img_8.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "线报采集"
    description = "人工加AI人工智能程序的自建首发源（双叠加和变价）"
    description2 = "基于全网大数据的分布式高性能爬虫采集源（低价商品和羊毛线报）"
    description3 = "与电商官方合作的输出源（淘礼金免单群 京礼金免单群 高佣商品）"
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "俱乐部"
    description = "MK俱乐部是一个很有意思的项目，可以让淘客无须写一行代码就可以拥有自己的线报网站"

    description3 = ""


    [[params.testimonials.item]]
      quote = "MK俱乐部可以自定义网站名字、LOGO，可以把我的查券网站和我的群号加在上面，变成我的专属线报网站。用它来引流、导流和留存用户非常不错，我很喜欢。"
      person = '微信返利群主'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "MK俱乐部可以由我设置数据源，把我群里的返利信息自动同步到我的专属线报网站上面，可以让没看到群消息的用户从这里选购商品，增加富裕佣金收入。"
      person = 'QQ返利群主'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "我在俱乐部的线报网站上面发布一些撸毛信息，可以引到很多垃圾佬，再从线报网站导流到群里，MK俱乐部是一个极好的引流工具。"
      person = '三三垃圾佬'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "发单工具"
    description = "功能强大，上手非常简单的自动发单工具，下载即用即开始躺赚"
    download = "功能强大，上手非常简单的自动发单工具，下载即用即开始躺赚"
    

    [[params.services.item]]
      title = "官方联盟"
      description = "使用自己的联盟账号，返利直接到联盟账号，官方联盟可查。软件不分佣金，直连官方联盟，走官方接口，无上级抽成。"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "微信QQ"
      description = "支持QQ和微信发单，羊毛线报。支持导购功能。微信使用中间页，支持自定义。支持发送组合凑单，发送券，发送店铺，发送会场。自动发送直播作业图，自动发送反馈图。"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "设置简单"
      description = "设置超简单，设置上返利账号和群号，就可以开始发单。将繁琐的复杂设置内部默认化，新手淘客3分钟就可以上手发单躺赚。"
      icon = "icon-video2"

      [[params.services.item]]
      title = "长久稳定"
      description = "全部使用官方接口和后台程序协议，不需要打开窗口，不会影响鼠标键盘操作，不影响干其他事情。长期高效稳定后台挂机运行。"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "淘客工具箱"
    description = "MK还免费提供淘客周边工具帮助大家更方便的做淘客赚佣金"

    [[params.about.item]]
      name = "黑名单提交及查询"
      position = "Web Designer"
      description = "违规引流和偷人的QQ号，发广告的人和商家，都可以上报。需要提供QQ号或者群号和证据截图。净化淘客环境，从我们做起。"
     

    [[params.about.item]]
      name = "豪车图分享下载"
      position = "http://www.mkstone.club:4000/account/image"
      description = "0撸图，bug价格图，可以上传到公开的MK俱乐部豪车分享栏目，同时你也可以下载别人分享过来的豪车图。用来引流效果很棒！"
     

    [[params.about.item]]
      name = "淘口令解析工具"
      position = "Web Designer"
      description = "把淘口令可以解析成链接，查看各种信息"



  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "MK业务总使用量"
      icon = "icon-briefcase"
      from = 0
      to = 16678
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "版本更新次数"
      icon = "icon-code"
      from = 0
      to = 2409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "被打赏次数"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "MK社群牛人"
      icon = "icon-people"
      from = 0
      to = 678
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = false
    title = "使用MK可以做哪些事情"
    description = "详细功能介绍和玩法"


  # Footer section
  [params.footer]
    enable = true

    copyright = '深圳市脉宽科技有限公司@版权所有'
   